### PR TITLE
Update es-actions to test various build options within x64 environment

### PR DESCRIPTION
**Pull request by clover2123**
Signed-off-by: HyukWoo Park <hyukwoo.park@samsung.com>

### CODE REVIEW

**Review by bbrto21 — APPROVED** [review]
LGTM

**Comment by ksh8281** [comment]
How about to check we can run sunspider after building small version of escargot?

**Comment by clover2123** [comment]
@ksh8281 
This patch already runs octane, v8, chakracore, spidermonkey, modifiedVendorTest, jsc-stress, **sunspider-js**, regression-tests, new-es, and intl for each escargot configurations including small version.
Is there anything you want more?

**Comment by ksh8281** [comment]
Oh, I see

**Review by ksh8281 — APPROVED** [review]

**Pull request merged**
