### PR TITLE
Allow using QuickJS RegExp engine

### PR DESCRIPTION
**Pull request by zherczeg**

### CODE REVIEW

**Comment by clover2123** [comment]
@zherczeg are you going to commit this pr to the master branch rather than `dev_regexp` branch?

**Comment by zherczeg** [comment]
I am a bit confused. I thought the plan for this branch is merging into master using GitHub after it is completed. Or do you need something else?

**Comment by zherczeg** [comment]
Patch is green and I think it is ready for review.

**Comment by clover2123** [comment]
Would you please measure the peformance and compare it with origin version(Yarr)?

**Comment by zherczeg** [comment]
The user time is measured on these tests:

regexp-dna.js:
  Yarr: 0m0.238s
  QuickJS: 0m0.513s

v8-regexp.js:
  Yarr: 0m1.415s
  QuickJS: 0m2.753s

QuickJS is roughly twice as slow. Do you need other tests?

**Comment by clover2123** [comment]
Thanks for your great contribution!
Since QuickJS is slower than Yarr, we may investigate it further to decide whether applying this patch or not.
Please leave it as it is for a while.

**Comment by ksh8281** [comment]
Super nice try!

**Comment by zherczeg** [comment]
This patch is not maintained at the moment, so I am closing it, but it can be reopened if needed.

**Pull request closed without merging**
