### PR TITLE
Implement String.fromCodePoint

### PR DESCRIPTION
**Pull request by rerobika**
Signed-off-by: Robert Fancsik <frobert@inf.u-szeged.hu>

### CODE REVIEW

**Comment by rerobika** [comment]
Note: The related V8 test cannot be enabled due to [this](https://github.com/Samsung/js_vendor_tc/blob/d70212863cc4d860ac9fcf02b3759a9cd1a2850b/v8/test/mjsunit/string-fromcharcode.js#L49) call. Without this line the test passes.

**Comment by ksh8281** [comment]
@rerobika How about add dummy function in `tools/test/v8/v8.mjsunit.js` for passing the test?

**Comment by rerobika** [comment]
@ksh8281 Good idea. :)

**Comment by rerobika** [comment]
@ksh8281 I've tried to apply your suggestion, but we have forgotten that the `%` character in the `%OptimizeFunctionOnNextCall` identifier, is not a valid identifier start character. So unfortunately we cannot use this trick.

**Comment by ksh8281** [comment]
@rerobika that's sad... :(

**Pull request merged**
