### PR TITLE
[WIP] Prevent [[Get]] call for proxy Objects in setObjectPreComputedCaseOperationCacheMiss

### PR DESCRIPTION
**Pull request by rerobika**
Signed-off-by: Robert Fancsik <frobert@inf.u-szeged.hu>

### CODE REVIEW

**Comment by ksh8281** [comment]
I think this is wrong
We need to get from propertydesc on it's prototype when property is on orgObject's prototype as js setter
I think `if (UNLIKELY(!originalObject->isInlineCacheable())) {` this wrong because it is doesn't care originalObject's prototype chain
We can check !isInlineCacheable is on it's prototype when gathering InlineCacheChainItem (1958~1963) I think

**Comment by rerobika** [comment]
@ksh8281 Would you like/do you have capacity to deal with this problem or shall I continue the work on it?

**Comment by ksh8281** [comment]
@rerobika You can work on this issue.
I think we need to add `testing isInlineCacheable` on getObjectPrecomputedCaseOperationCacheMiss too

**Comment by rerobika** [comment]
Temporary I close this issue, I'll reopen if I found the proper solution.

**Pull request closed without merging**
