### PR TITLE
Implement getting object properties.

### PR DESCRIPTION
**Pull request by zherczeg**
Furthermore extend get scope and get scope variables with state index parameter.

### CODE REVIEW

**Comment by zherczeg** [comment]
I get a fail `escargot-pr_PR-680/test/vendortest/Escargot/new-es/generator.js`, but I don't think my patch has anything to do with that. Do you have any idea?

**Comment by ksh8281** [comment]
You can check vendortest submodule version

**Comment by zherczeg** [comment]
You are right, I have accidentally committed it.

**Comment by zherczeg** [comment]
@ksh8281 could you check this patch? Thank you!

**Comment by zherczeg** [comment]
@clover2123 Could you check this patch?

**Pull request merged**
