### PR TITLE
Fix JSON.stringify property order

### PR DESCRIPTION
**Pull request by Achie72**
Signed-off-by: Bela Toth tbela@inf.u-szeged.hu

### CODE REVIEW

**Comment by ksh8281** [comment]
Do you have TC or spec for this?
I cannot understand why we should remove fast-path of JSON.stringify.

**Comment by Achie72** [comment]
```js
function test() {
        var obj = {
          2: true,
          0: true,
          1: true,
          ' ': true,
          9: true,
          D: true,
          B: true,
          '-1': true
        };
        obj.A = true;
        obj[3] = true;
        "EFGHIJKLMNOPQRSTUVWXYZ".split('').forEach(function(key){
          obj[key] = true;
        });
        Object.defineProperty(obj, 'C', { value: true, enumerable: true });
        Object.defineProperty(obj, '4', { value: true, enumerable: true });
        delete obj[2];
        obj[2] = true;

        return JSON.stringify(obj)
          //'{"0":true,"1":true,"2":true,"3":true,"4":true,"9":true," ":true,"D":true,"B":true,"-1":true,"A":true,"E":true,"F":true,"G":true,"H":true,"I":true,"J":true,"K":true,"L":true,"M":true,"N":true,"O":true,"P":true,"Q":true,"R":true,"S":true,"T":true,"U":true,"V":true,"W":true,"X":true,"Y":true,"Z":true,"C":true}';
}

print(test())
```

This is a kangax tests, but also a behaviour error. The out commented string should be the results, as JSON should list array indecies first, but without this patch, the listing is incorrect. (for example, the 2 is at the very and of it)

**Comment by ksh8281** [comment]
Oh, I see.

**Comment by clover2123** [comment]
@Achie72 
BTW the author info(mail address) of this pr and other commits of yours seems incorrectly written.
Have you noticed this?
I'm wondering if this is intended.

**Comment by Achie72** [comment]
No, i haven't noticed it. This is interesting, as my setup is the same since like almost a year, gonna look into what may happened.

**Comment by Achie72** [comment]
I think it should be fixed, somehow my gitconfig file had incorrect data in it, i suppose that messed it up.

**Comment by clover2123** [comment]
@Achie72 
Do you want other wrong infos in git history to be fixed as well?

**Comment by Achie72** [comment]
If you don't mind, then i'm fine with it, in that case it's just unnecessary fiddling around.

**Comment by clover2123** [comment]
@Achie72 Thanks. I confirmed that this pr has the correct author info, so merged this patch.

**Pull request merged**
