### PR TITLE
Implement basic tail call optimization for normal function

### PR DESCRIPTION
**Pull request by clover2123**

### CODE REVIEW

**Comment by clover2123** [comment]
Performance Result
* Linux-x64 : 2516 -> 2535
* Linux-ARM: 572 -> 580

Slightly increase the octance score, but need to further tune TCO in following patches

**Comment by ksh8281** [comment]
Can we use ExecutionState::resolveCallee instead of adding another parameter to Interpreter::interpret

**Comment by clover2123** [comment]
@ksh8281 Good suggestion!
I fixed this patch as you commented, 
but it needs some adjustment because newly added bytecodes affect the overall interpreter performance 😢

**Comment by clover2123** [comment]
#### Origin
Richards: 1340
DeltaBlue: 1102
Crypto: 2081
RayTrace: 1291
EarleyBoyer: 1771
RegExp: 437
Splay: 967
SplayLatency: 1899
NavierStokes: 2814
PdfJS: 5296
Mandreel: 1233
MandreelLatency: 7565
Gameboy: 8719
CodeLoad: 18423
Box2D: 5209
zlib: 2634
Typescript: 8066
**Score (version 9): 2631**

#### TCO
Richards: 1399
DeltaBlue: 1137
Crypto: 1967
RayTrace: 1306
EarleyBoyer: 1849
RegExp: 439
Splay: 1019
SplayLatency: 1969
NavierStokes: 2870
PdfJS: 5315
Mandreel: 1223
MandreelLatency: 7497
Gameboy: 8934
CodeLoad: 18487
Box2D: 5498
zlib: 2644
Typescript: 7936
**Score (version 9): 2669**

I adjusted the order of bytecode routine in the interpreter and got the above result.
In octane benchmark, tail recursion is rarely occurred, so TCO could not obtain a significant performance gain 😢

**Review by ksh8281 — APPROVED** [review]

**Pull request merged**
