### PR TITLE
Support more class static initializer features

### PR DESCRIPTION
**Pull request by zherczeg**

### CODE REVIEW

**Comment by zherczeg** [comment]
I found an unrelated issue, but it fixes static initializer tests:
```
'use strict';
(function({a = b = c}) { })();
```

Throws: `SyntaxError: Line 71: Invalid left-hand side in assignment`

Basically the b = c is not accepted in object destructuring assignments

**Review by ksh8281 — APPROVED** [review]
Good!

**Comment by zherczeg** [comment]
Patch is updated, `static-init` tests are passed now.

**Review by clover2123 — APPROVED** [review]
LGTM

**Pull request merged**
