### PR TITLE
Support class static initializers

### PR DESCRIPTION
**Pull request by zherczeg**

### CODE REVIEW

**Comment by zherczeg** [comment]
Apparently some identifiers such as await/yield/arguments cannot be used as identifiers in static initializers (looks like an extra condition). Is there an easy way to prevent their use?

**Comment by zherczeg** [comment]
The patch looks working now. The code has some complicated checks, I hope reviewers may suggest improvements for them.

**Review by ksh8281 — APPROVED** [review]
Looks Good!

**Review by clover2123 — APPROVED** [review]
I think that thouse extra checks are inevitable.
LGTM

**Pull request merged**
